name: ARMOYUPlugin
version: '1.0-SNAPSHOT'
main: com.armoyu.minecraftplugin
api-version: 1.21
commands:
  tpa:
    description: Bir oyuncuya teleportlanma isteği göndermeye yarar.
    usage: /tpa Player
  tpaccept:
    description: tp isteği kabul edilmesi
    usage: /tpaccept
  tpdeny:
    description: tp isteği reddilmesi
    usage: /tpdeny
  login:
    description: Oyuncuyu giriş yapmaya zorlar
    usage: /login <parola>
  register:
    description: Oyuncuyu kayıt eder
    usage: /register <parola>